# Generated by Django 2.2 on 2021-11-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0003_auto_20211029_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='right', max_length=255),
            preserve_default=False,
        ),
    ]
