# Generated by Django 2.2 on 2021-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0004_auto_20211101_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
