# Generated by Django 2.2 on 2021-11-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0005_userprofile_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='NAME STRING', max_length=255),
        ),
    ]
